Get http://localhost:3005/players/
###

Get http://localhost:3005/players/3
###
Get http://localhost:3003/players/1/playerScores

###

Put http://localhost:3003/players/3/
Content-Type: application/json

{
  "playerName": "Raju"
}

###

Get http://localhost:3003/matches/18/

###
Get http://localhost:3003/matches/18/players